import type { Metadata } from "next";
import { Sansita, Noto_Sans, Merriweather, Oswald } from 'next/font/google'
import "./globals.css";

const sansita = Sansita({
  weight: ["900"],
  subsets: ["latin"],
  variable: "--font-sansita",
});

const noto = Noto_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-noto",
});

const marriweather = Merriweather({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-marriweather",
})

const oswald = Oswald({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-oswald",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sansita.variable} ${noto.variable} ${marriweather.variable} ${oswald.variable} antialiased`}
      >
        <svg
          className="pointer-events-none fixed isolate z-50 opacity-70 mix-blend-soft-light"
          width="100%"
          height="100%"
        >
          <filter id="noise">
            <feTurbulence
              type="fractalNoise"
              baseFrequency="0.80"
              numOctaves="4"
              stitchTiles="stitch"
            />
          </filter>
          <rect width="100%" height="100%" filter="url(#noise)" />
        </svg>

        <div className="layout-sm relative z-10 grid gap-y-8 px-4 xl:layout-xl xl:gap-x-8 xl:px-0 [&>*]:col-start-2 xl:[&>*]:col-start-3">
         {children}

	 <div className="mt-6" />
	</div>
      </body>
    </html>
  );
}
